package(default_visibility = ["//visibility:public"])

py_library(
    name = "tensorflow_zero",
    srcs = ["__init__.py"],
    srcs_version = "PY2AND3",
    deps = [
        "//tensorflow_zero/python:zero_ops_py",
    ],
)
